version: "3.9"
services:
  web:
    build: /
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on:
      - redis
  redis:
    image: "redis"
    command: redis-server
    ports:
      - "6379:6379"
  sidekiq:
    depends_on:
      - "redis"
    build: .
    command: bundle exec sidekiq
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
